%% This file runs the different algos on some datasets...
clear
% Init data and paths.
load data.mat
addpath('Percetron')
addpath('Naive Bayes')
addpath('SVM')
addpath('K Nearest')

N_PERCEPTRON_ITERATIONS = 25;
N_AVG_PERCEPTRON_ITERATIONS = 25;
KNN_K = 20;

nWords = max(cellfun(@(x) max(x.id), wordcount));

algorithms = { ...
    @(training_data, training_labels, test_data) ...
        run_perceptron(training_data, training_labels, test_data, N_PERCEPTRON_ITERATIONS), ...
    @(training_data, training_labels, test_data) ...
        run_naivebayes(training_data, training_labels, test_data, nWords), ...
    @(training_data, training_labels, test_data) ...
        run_average_perceptron(training_data, training_labels, test_data, N_AVG_PERCEPTRON_ITERATIONS), ...
    @(training_data, training_labels, test_data) ...
        run_knn(training_data, training_labels, test_data, nWords, KNN_K) ...
};

for algoIndex = 1:size(algorithms,2)
    % disp('Running');
    [error, timing] = test_algorithm( algorithms{algoIndex}, wordcount, labels_sentiment, wordcount, labels_sentiment, 1)
    % disp('Done');
end